### ISSUE TITLE
Wrong return value in BinarySearchIterative.py

### ISSUE THREAD

**Issue by NotTheMomma1** [KlaraOppenheimerSchule/12FIAE_Modulescode#1]
12FIAE_Modulescode/Module Aktivitätsdiagramm/Einfache_Programmstruktur /BinarySearchIterative.py

Wrong return value,

Expected behaviour: returns iterations

Actual behaviour: returns index of mid when element found

suggested changes:

line 26: return mid -> return iterations

**Comment by Creis2k** [comment]
I can approve it
